databases:
  - name: senri_DB
    databaseName: senri_db
    user: senri
    region: singapore

services:
  - type: web
    name: senri
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: senri_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false